COPERNICUS_API=https://catalogue.dataspace.copernicus.eu/odata/v1/Products
COPERNICUS_TOKEN=https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token
LANDSAT_API=https://m2m.cr.usgs.gov/api/api/json/stable/
LANDSAT_TOKEN=
LANDSAT_USER=
COPERNICUS_USERNAME=
COPERNICUS_PASSWORD=
COPERNICUS_FOLDER= imagesFolder
COPERNICUS_PREVIEW_FOLDER= imagesPreviewFolder
